import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className+' bg-light w-full min-h-screen'}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
